package generation

var (
	mainTemplate = `// Code generated by cool go-validate tool; DO NOT EDIT.
package {{ .PackageName }}

import (
	"errors"
	"strings"
	"strconv"
)

type ValidationError struct {
	Field string
	Err error
}
{{range .ValidateMethods}}
{{.}}
{{end}}

`
	validateFuncTemplate = `func (%s %s) Validate() (validationErrors []ValidationError, err error)  {
		
	return 
}`
)
